//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int booking_id { get; set; }
        public int cust_id { get; set; }
        public String name { get; set; }
        public int flight_id { get; set; }
        public DateTime flight_date { get; set; }
        public TimeSpan flight_time { get; set; }
        public String duration { get; set; }
        public String destination { get; set; }
        public String plane_company { get; set; }
        public String plane_name { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
